#!/usr/bin/env node
/**
 * The two images in the README, rendered from **synthetic** data.
 *
 * The README needs to show what this server produces — a chart is not describable in a bullet list —
 * and the obvious way to get one is a screenshot of a real call. That would put a real symbol's real
 * prices, on a real date, from the maintainer's own session, into a public repository forever. So
 * the data here is generated by a seeded pseudo-random walk and both captions say so.
 *
 * Deterministic on purpose: the same script produces the same bytes, so regenerating does not create
 * a diff unless the renderer actually changed. `Math.random` is therefore not used — a fixed LCG is.
 *
 * Both renderers emit pure SVG with no `<style>` and no `<script>`, which is what lets GitHub render
 * them inline in a README rather than showing a broken image.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { renderCandles } from "../src/render/candles.js";
import { renderSankey, type FlowBroker } from "../src/render/sankey.js";
import { bollinger, macd, rsi, sma } from "../src/core/indicators.js";
import type { Bar } from "../src/core/bars.js";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "docs", "images");

/** A linear congruential generator. Fixed seed, so the output is byte-stable across runs. */
function lcg(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state * 1_664_525 + 1_013_904_223) >>> 0;
    return state / 0x1_0000_0000;
  };
}

/**
 * A plausible daily series: a gentle uptrend with a mid-series pullback.
 *
 * Shaped rather than pure noise, because the point of the image is to show what the overlays and
 * panels do — a random walk with no structure makes the moving averages and the RSI panel look
 * like decoration.
 */
function syntheticBars(count: number): Bar[] {
  const rand = lcg(20260825);
  const bars: Bar[] = [];
  let price = 3800;
  const start = Date.UTC(2026, 0, 5); // a Monday

  for (let i = 0; i < count; i++) {
    const trend = i < count * 0.55 ? 4.5 : i < count * 0.72 ? -9 : 7;
    const noise = (rand() - 0.5) * 70;
    price = Math.max(1500, price + trend + noise);

    const open = price - (rand() - 0.5) * 30;
    const close = price;
    const high = Math.max(open, close) + rand() * 35;
    const low = Math.min(open, close) - rand() * 35;
    const volume = Math.round(120_000 + rand() * 180_000 + (Math.abs(close - open) > 25 ? 90_000 : 0));

    // Weekdays only, so the axis reads like a trading calendar.
    const day = new Date(start + Math.floor(i / 5) * 7 * 86_400_000 + (i % 5) * 86_400_000);
    bars.push({
      date: day.toISOString().slice(0, 10),
      open: Math.round(open),
      high: Math.round(high),
      low: Math.round(low),
      close: Math.round(close),
      average: Math.round((high + low + close) / 3),
      volume,
      value: Math.round(volume * 100 * close),
      frequency: Math.round(400 + rand() * 900),
      change: Math.round(close - open),
      changePercent: Number((((close - open) / open) * 100).toFixed(2)),
      // Foreign flow is part of a real bar; synthetic values keep the shape honest without
      // implying anybody's actual position.
      foreignBuy: Math.round(volume * 0.3),
      foreignSell: Math.round(volume * 0.24),
      netForeign: Math.round(volume * 0.06),
    });
  }
  return bars;
}

function priceChart(): string {
  const bars = syntheticBars(140);
  const closes = bars.map((b) => b.close);
  const bands = bollinger(closes, 20, 2);
  const m = macd(closes);

  const swingLow = Math.min(...closes.slice(-40));
  const swingHigh = Math.max(...closes.slice(-40));

  return renderCandles({
    symbol: "DEMO",
    bars,
    title: "DEMO — daily",
    subtitle: "Synthetic data. This is what `price_chart` returns; nothing here is a real quote.",
    overlays: [
      { label: "SMA(20)", series: sma(closes, 20) },
      { label: "SMA(50)", series: sma(closes, 50) },
      { label: "BB upper", series: bands.upper, dashed: true },
      { label: "BB lower", series: bands.lower, dashed: true },
    ],
    subPanels: [
      {
        label: "RSI(14)",
        series: [{ label: "RSI", series: rsi(closes, 14) }],
        guides: [30, 70],
        range: [0, 100],
      },
      {
        label: "MACD(12,26,9)",
        series: [
          { label: "MACD", series: m.macd },
          { label: "signal", series: m.signal },
        ],
        histogram: m.histogram,
      },
    ],
    annotations: [
      { kind: "level", price: swingHigh, label: "resistance", dashed: true },
      { kind: "level", price: swingLow, label: "support", dashed: true },
    ],
    showVolume: true,
  });
}

function brokerFlow(): string {
  // Real IDX broker codes, entirely invented volumes. The codes are public exchange identifiers;
  // what is private is who traded what, and none of that is here.
  const brokers: FlowBroker[] = [
    {
      code: "ZP",
      investorType: "Asing",
      amount: 184_000_000_000,
      distributedWith: [
        { code: "YP", investorType: "Lokal", amount: 82_000_000_000 },
        { code: "CC", investorType: "Lokal", amount: 51_000_000_000 },
        { code: "NI", investorType: "Lokal", amount: 34_000_000_000 },
        { code: "MG", investorType: "Asing", amount: 17_000_000_000 },
      ],
    },
    {
      code: "AK",
      investorType: "Asing",
      amount: 121_000_000_000,
      distributedWith: [
        { code: "YP", investorType: "Lokal", amount: 54_000_000_000 },
        { code: "DX", investorType: "Asing", amount: 39_000_000_000 },
        { code: "BK", investorType: "Lokal", amount: 28_000_000_000 },
      ],
    },
    {
      code: "BK",
      investorType: "Lokal",
      amount: 76_000_000_000,
      distributedWith: [
        { code: "CC", investorType: "Lokal", amount: 41_000_000_000 },
        { code: "NI", investorType: "Lokal", amount: 21_000_000_000 },
        { code: "PD", investorType: "Pemerintah", amount: 14_000_000_000 },
      ],
    },
    {
      code: "DX",
      investorType: "Asing",
      amount: 58_000_000_000,
      distributedWith: [
        { code: "YP", investorType: "Lokal", amount: 33_000_000_000 },
        { code: "MG", investorType: "Asing", amount: 25_000_000_000 },
      ],
    },
  ];

  return renderSankey(brokers, {
    symbol: "DEMO",
    unit: "IDR",
    from: "2026-07-01",
    to: "2026-07-31",
    board: "REGULER",
    topSources: 4,
    topTargets: 6,
  });
}

function write(name: string, svg: string): void {
  const path = join(OUT, name);
  writeFileSync(path, svg.endsWith("\n") ? svg : `${svg}\n`, "utf8");
  // GitHub refuses to render an SVG that carries a script, so a regression there is worth catching
  // at generation time rather than as a broken image in the README.
  if (/<script|<style/i.test(svg)) {
    throw new Error(`${name} contains a <script> or <style> element; GitHub will not render it inline.`);
  }
  console.log(`${name} — ${(svg.length / 1024).toFixed(1)} KB`);
}

mkdirSync(OUT, { recursive: true });
write("price-chart-sample.svg", priceChart());
write("broker-distribution-sample.svg", brokerFlow());
